---
  - name: Enable container features
    replace:
      path: /boot/firmware/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
    with_items:
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
    notify:
      - Reboot host and wait for it to restart

  - name: Install microk8s
    community.general.snap:
      name: microk8s
      classic: true
