---
- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

- name: start microk8s
  become: yes
  command: microk8s start

- name: initialize microk8s cluster
  become: yes
  command: "kubectl label nodes {{ inventory_hostname }} node-role.kubernetes.io/control-plane=''"
  when: "'controlplane' in group_names"
